### ISSUE TITLE
Formatierung verbessern

### ISSUE THREAD

**Issue by JenniferLiske** [Bibmann/Datenintensive-Prozesse-SBK#1]
Hallo,
um deinen Beitrag übersichtlicher zu gestalten kannst du deine Formatierung verbessern. Zum Beispiel bei den Punkten 2.1 und 2.2 die beschriebenen Prozesse Fremddatenübernahme, Daten-Korrektur, Routine Tätigkeit „Operating“ und Datensicherung fett machen und einen Absatz machen.

**Comment by Bibmann** [comment]
Danke für den Hinweis
